apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pcjoshiatseasampleshopapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pcjoshiatseasampleshopapp 
    spec:
      containers:
        - name: pcjoshiatseasampleshopapp 
          image: rlincregistry.azurecr.io/pcjoshiatseasampleshopapp
          ports:
          - containerPort: 80